kind: Inventory
data:
- name: Stops
  ref: <Stops>
  phones:
  - t
  - k
  - ''''
- name: Nasals
  ref: <N>
  phones:
  - m
  - n
- name: Fricatives
  ref: <Frc>
  phones:
  - h
  - s
- name: Sonorants
  ref: <Son>
  phones:
  - l
  - y
  - w
- name: Vowels
  ref: <V>
  phones:
  - a
  - e
  - i
  - o
  - u
  - v
- name: Temp Tags
  ref: <TempTags>
  tags:
  - '[TEMP]'
  - '[TEMP_VOWEL]'
  - '[TEMP_VOWEL_A]'
  - '[TEMP_VOWEL_E]'
  - '[TEMP_VOWEL_I]'
  - '[TEMP_VOWEL_O]'
  - '[TEMP_VOWEL_U]'
  - '[TEMP_VOWEL_V]'
  - '[TEMP_LAT]'
  - '[TEMP_DROP]'
  - '[TEMP_GLOT]'
  - '[TEMP_H]'
  - '[TEMP_LAT_H]'
  - '[TEMP_GLOT_H]'
  - '[TEMP_VOWEL_H]'
  - '[TEMP_VOWEL_A_H]'
  - '[TEMP_VOWEL_E_H]'
  - '[TEMP_VOWEL_I_H]'
  - '[TEMP_VOWEL_O_H]'
  - '[TEMP_VOWEL_U_H]'
  - '[TEMP_VOWEL_V_H]'
- name: PPP
  ref: <PPP>
  tags:
  - '[WI]'
  - '[DIST]'
  - '[DIST=de]'
  - '[DIST=di]'
- name: H_alt
  ref: <H_alt>
  tags:
  - '[H_alt=none]'
  - '[H_alt=drop]'
  - '[H_alt=glot]'
  - '[H_alt=lat]'
  - '[H_alt=vowel_a]'
  - '[H_alt=vowel_e]'
  - '[H_alt=vowel_i]'
  - '[H_alt=vowel_o]'
  - '[H_alt=vowel_u]'
  - '[H_alt=vowel_v]'
