kind: Inventory
data:
- name: Stops
  ref: <Stops>
  phones:
  - t
  - k
  - ''''
- name: Nasals
  ref: <N>
  phones:
  - m
  - n
- name: Fricatives
  ref: <Frc>
  phones:
  - h
  - s
- name: Sonorants
  ref: <Son>
  phones:
  - l
  - y
  - w
- name: Vowels
  ref: <V>
  phones:
  - a
  - e
  - i
  - o
  - u
  - v
- name: Temp Tags
  ref: <TempTags>
  tags:
  - '[TEMP]'
  - '[TEMP_VOWEL]'
  - '[TEMP_LAT]'
  - '[TEMP_DROP]'
  - '[TEMP_GLOT]'
  - '[TEMP_H]'
  - '[TEMP_LAT_H]'
  - '[TEMP_GLOT_H]'
  - '[TEMP_VOWEL_H]'
- name: PPP
  ref: <PPP>
  tags:
  - '[WI]'
  - '[DIST]'
  - '[DIST=de]'
  - '[DIST=di]'
- name: H_alt
  ref: <H_alt>
  tags:
  - '[H_alt=none]'
  - '[H_alt=drop]'
  - '[H_alt=glot]'
  - '[H_alt=lat]'
  - '[H_alt=vowel]'
- name: PrefixClass
  ref: <PrefixClass>
  tags:
  - '[PrefixClass=a_stem]'
  - '[PrefixClass=v_stem]'
  - '[PrefixClass=e_stem]'
  - '[PrefixClass=k_a_stem]'
  - '[PrefixClass=vowel_stem]'
  - '[PrefixClass=cons_stem]'
  - '[PrefixClass=r_stem]'
- name: Pro
  ref: <Pro>
  tags:
  - '[Pro=1sg.A]'
  - '[Pro=Edl.A]'
  - '[Pro=Epl.A]'
  - '[Pro=Idl.A]'
  - '[Pro=Ipl.A]'
  - '[Pro=2sg.A]'
  - '[Pro=2dl.A]'
  - '[Pro=2pl.A]'
  - '[Pro=3sg.A]'
  - '[Pro=3ns.A]'
  - '[Pro=1sg.B]'
  - '[Pro=Edl.B]'
  - '[Pro=Epl.B]'
  - '[Pro=Idl.B]'
  - '[Pro=Ipl.B]'
  - '[Pro=2sg.B]'
  - '[Pro=2dl.B]'
  - '[Pro=2pl.B]'
  - '[Pro=3sg.B]'
  - '[Pro=3ns.B]'
  - '[Pro=1sg>3sg]'
  - '[Pro=2sg>3sg]'
- name: AspectClass
  ref: <AspectClass>
  tags:
  - '[AspectClass=a]'
  - '[AspectClass=become]'
  - '[AspectClass=ko-kots]'
  - '[AspectClass=sk-s-hi-hihst]'
  - '[AspectClass=sk-s-a]'
  - '[AspectClass=sk-s-hst]'
  - '[AspectClass=sk-s-la]'
  - '[AspectClass=sk-h]'
  - '[AspectClass=sk-h-yh]'
  - '[AspectClass=hvsk-han]'
  - '[AspectClass=hvsk-nh]'
  - '[AspectClass=hvsk-n]'
  - '[AspectClass=husk]'
  - '[AspectClass=episodic]'
  - '[AspectClass=terminative]'
  - '[AspectClass=terminative-no-o]'
  - '[AspectClass=e-aka]'
  - '[AspectClass=e-a]'
  - '[AspectClass=apl-active]'
  - '[AspectClass=apl-active-h]'
  - '[AspectClass=apl-active-'']'
  - '[AspectClass=apl-active-a]'
  - '[AspectClass=apl]'
  - '[AspectClass=go]'
  - '[AspectClass=go-in]'
  - '[AspectClass=cause]'
  - '[AspectClass=ih-il]'
  - '[AspectClass=hih-hil]'
  - '[AspectClass=hih-hilh]'
  - '[AspectClass=hih-lh]'
  - '[AspectClass=ih-vh]'
  - '[AspectClass=vnh-ih-a]'
  - '[AspectClass=vnh-vsk]'
  - '[AspectClass=i-vka]'
  - '[AspectClass=i-a-i]'
  - '[AspectClass=i-a-ihsk]'
  - '[AspectClass=ih-ihi]'
  - '[AspectClass=o]'
  - '[AspectClass=be-at]'
  - '[AspectClass=oh-al]'
  - '[AspectClass=oh-ol]'
  - '[AspectClass=v-vhs]'
  - '[AspectClass=vsk]'
  - '[AspectClass=vsk-long]'
  - '[AspectClass=vsk-post-v]'
  - '[AspectClass=rev-gi]'
  - '[AspectClass=rev-i]'
  - '[AspectClass=rev-''i]'
  - '[AspectClass=rev-e]'
  - '[AspectClass=stative]'
  - '[AspectClass=stative-k]'
  - '[AspectClass=stative-h]'
  - '[AspectClass=stative-s]'
  - '[AspectClass=stative-a'']'
  - '[AspectClass=stative-eh]'
- name: Variant
  ref: <Variant>
  tags:
  - '[Variant=2]'
  - '[Variant=3]'
  - '[Variant=4]'
- name: Aspect
  ref: <Aspect>
  tags:
  - '[Aspect=present]'
  - '[Aspect=incompletive]'
  - '[Aspect=completive]'
  - '[Aspect=immediate]'
  - '[Aspect=infinitive]'
- name: TenseClass
  ref: <TenseClass>
  tags:
  - '[TenseClass=a_present]'
  - '[TenseClass=i_present]'
- name: Tense
  ref: <Tense>
  tags:
  - '[Tense=present]'
  - '[Tense=immediate]'
  - '[Tense=habitual]'
  - '[Tense=future_prog]'
  - '[Tense=assertive]'
  - '[Tense=reported]'
  - '[Tense=infinitive]'
- name: Legacy Tags
  ref: <LegacyTags>
  tags:
  - '[Pro]'
  - '[Aspect]'
  - '[Tense]'
