stages:
  - aspect_suffix
  - drop_stem_initial_vowel
  - pronominal

# Inflectional Features (originally from verb_features.yaml)
features:
  pronominal:
    - 1sg.A
    - Edl.A
    - Epl.A
    - Idl.A
    - Ipl.A
    - 2sg.A
    - 2dl.A
    - 2pl.A
    - 3sg.A
    - 3ns.A
    - 1sg.B
    - Edl.B
    - Epl.B
    - Idl.B
    - Ipl.B
    - 2sg.B
    - 2dl.B
    - 2pl.B
    - 3sg.B
    - 3ns.B
  aspect:
    - present
    - immediate
    - incompletive
    - completive
    - infinitive

# Lexical features and metadata (originally from verb.yaml)
lexical_features:
  - prefix_class
  - aspect_class

paradigm:
  generate_contingent_markers: true
